### PR TITLE
Add functionality to send event to multiple addresses at once

### LINKED ISSUE #8: Multiple Discord Hook Support
Hi i want to request support to multiple discord hooks, its awesome and its so great how this works, maybe a recursive WEBHOOK_URL Env Variable recognition or array?

Keep the good work 👍

### PR DESCRIPTION
**Pull request by JustArchi**
Closes #8

### CODE REVIEW

**Comment by k3rn31p4nic** [comment]
I'll test & review this before I merge. Is it a breaking change? Will it affect users who are already using this?

**Comment by JustArchi** [comment]
No, this is not a breaking change, existing setups will work as before. The main difference is how previously `WEBHOOK_URL: "addr1.com addr2.com"` didn't work at all, and now works as expected, by sending a webhook update to `addr1.com` and `addr2.com`.

Of course you're more than welcome to test this change, but unless somebody is using a webhook with space in the URL, this should not regress on any setup. And even if somebody has spaces in his URL, he should escape them with `%20` anyway as required by RFC.

**Review by k3rn31p4nic — APPROVED** [review]

**Comment by k3rn31p4nic** [comment]
Thanks for the contribution, would you also like to implement this in [appveyor-discord-webhook](https://github.com/DiscordHooks/appveyor-discord-webhook), [gitlab-ci-discord-webhook](https://github.com/DiscordHooks/gitlab-ci-discord-webhook), and [github-actions-discord-webhook](https://github.com/DiscordHooks/github-actions-discord-webhook)?

**Comment by JustArchi** [comment]
Sure thing, I'll do last 2, I'm not entirely sure how to do it in powershell as my knowledge is more limited there. Feel free to cover the first one if you'd like to, as the concept is similar 👍

**Comment by k3rn31p4nic** [comment]
Cool, thanks. Also, I won't be taking up the task as I want to open it for Hacktoberfest for new contributors. So, if anyone else wants to take it, feel free to do so: https://github.com/DiscordHooks/appveyor-discord-webhook/issues/14

**Pull request merged**
