### PR TITLE
adding support for travis-ci.com

### PR DESCRIPTION
**Pull request by fareszr**
i was super confused when the travis vot was showing success and github showing failure
turns out your script uses travis-ci.org!
according to travis them selves new users should use travis-ci.com 
so i added an alternative script for travis-ci.com

### CODE REVIEW

**Comment by fareszr** [comment]
there is a bug the build fails but the bot says it passed
idk if its from the new script tho

**Comment by k3rn31p4nic** [comment]
The script already supports travis-ci.com. It only uses the icons from travis-ci.org. What did you add that adds _support_ for travis-ci.com?

**Comment by fareszr** [comment]
before i changed the script 
the bot was using travis-ci.org
after recreating the bot it now uses travis-ci.com with the correct build number
but it has the aforementioned bug

**Comment by k3rn31p4nic** [comment]
It already supports travis-ci.com. Your script only changes the domains of the icons to the travis-ci.com. Your script doesn't add any code changes that adds "support" for travis-ci.com as you say. Please check for yourself the difference between your script and the already existing script. It doesn't add anything. Feel free to correct me if I'm wrong (spoiler alert, I'm not).

**Pull request closed without merging**
